### ISSUE TITLE
[Interpreter] Error upon get_tests() execution

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#11]
Using the following entry:

get_tests("TBTAF Smoke test project 01",["TBTAF"],IN)

I'm getting the following output at the end:

Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 61, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\interpreter\TBTAFInterpreter.py", line 115, in parseScript
    raise e
TypeError: getTestCases() takes exactly 1 argument (3 given)

Please investigate and reassign if required.

**Comment by luisdani2090** [comment]
I'm getting an error in the orchestrator line 180
@erflogo 

  File "C:\Users\Daniel\Desktop\tbtaf\interpreter\TBTAFOrchestrator.py", line 180, in getTests
    queriedTests = tbTestSuite.getTestCases(tagList, filterType)
TypeError: getTestCases() takes exactly 1 argument (3 given)

**Comment by pacoalan** [comment]
Fixed method getTests() in TBTAFOrchestrator.py. We had tbTestSuite.getTestSuiteType instead of tbTestSuite.getTestSuiteType() when getting the test suite type.

Now you would get an error we defined which we think is expected. @luisdani2090 , @carofermin , @S41nz , please let us know what you think. In test01.tbtaf, given the test suite created is Normal, we shouldn't receive as argument a list of tags. The created test suite will be from the class TBTestSuite and not TBSmartTestSuite, which has the getTestCases() method with three parameters. 

I would change last line to: get_tests("TBTAF Smoke test project 01")
